version: "3.9"
services:
  mc:
    image: itzg/minecraft-server:latest
    container_name: mc
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      VERSION: "LATEST"
      ONLINE_MODE: "TRUE"
      MEMORY: "4G"
      ENABLE_RCON: "true"
      RCON_PASSWORD: "${RCON_PASSWORD}"
      RCON_PORT: "25575"
    volumes:
      - ./server/data:/data
    restart: unless-stopped
